name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node-duckdb
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - name: Checkout duckdb
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'duckdb/duckdb'
          path: duckdb  
      - name: Setup cross toolchain
        # Alpine 3.15 ships with libstc++.28 so we must build with gcc 10 until 3.16 is shipped
        run: |
          sudo apt-get remove libc6-dev libssl-dev -y -qq
          sudo apt-get install ninja-build
          wget -q http://more.musl.cc/10/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
      - name: Build & install OpenSSL 1.1.1
        run: |
          export AMUSL=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-
          wget https://www.openssl.org/source/openssl-1.1.1n.tar.gz
          tar -xf openssl-1.1.1n.tar.gz
          cd openssl-1.1.1n
          ./Configure linux-aarch64 --cross-compile-prefix=$(echo $AMUSL) --prefix=/usr/local/ssl --openssldir=/usr/local/ssl no-zlib shared CXXFLAGS=-fPIC
          sudo make
          sudo make install_sw
      - name: Build DuckDB & node-duckdb
        env:
          BUILD_JSON: 1
          BUILD_HTTPFS: 1
          BUILD_FTS: 1
          OPENSSL_ROOT_DIR: /usr/local/ssl
          GEN: ninja
        run: |
          export CC=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
          export CXX=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++
          yarn install --ignore-scripts && cd duckdb && make && cd - && yarn build:addon
      - run: |
          zip -j node-duckdb-arm64-musl.zip build/Release/libduckdb.so build/Release/node-duckdb-addon.node
          zip -j duckdb_cli-arm64-musl.zip duckdb/build/release/duckdb
      - uses: actions/upload-artifact@v3
        with:
          name: node-duckdb-arm64
          path: |
            node-duckdb-arm64-musl.zip
      - uses: actions/upload-artifact@v3
        with:
          name: duckdb-cli-arm64
          path: |
            duckdb_cli-arm64-musl.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            duckdb_cli-arm64-musl.zip
            node-duckdb-arm64-musl.zip
      
