name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node-duckdb
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - name: Checkout duckdb
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'duckdb/duckdb'
          path: duckdb
      - run: |
          wget -q https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
      - name: Install OpenSSL 1.1.1
        run: |
          export AMUSL=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-
          wget https://www.openssl.org/source/openssl-1.1.1n.tar.gz
          tar -xf openssl-1.1.1n.tar.gz
          cd openssl-1.1.1n
          ./Configure linux-aarch64 --cross-compile-prefix=$(echo $AMUSL) --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -static no-zlib
          sudo make
          sudo make install
          sudo sh -c "echo '/usr/local/ssl/lib' >> /etc/ld.so.conf.d/openssl-1.1.1n.conf"
          sudo ldconfig -v
      - name: Install modules and build
        run: |
          sudo apt-get purge libc6 libc6-dev -y -qq
          export CC=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
          export CXX=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++
          yarn install --ignore-scripts && yarn build:duckdb && yarn build:addon
      - run: |
          zip -j build-arm64.zip build/Release
      - uses: actions/upload-artifact@v2
        with:
          name: node-duckdb-arm64
          path: |
            node-duckdb-arm64.zip
