name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Checkout node-duckdb
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - name: Checkout duckdb
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'duckdb/duckdb'
      - run: cd ../.. && ls
      - run: |
          wget -q https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
      - name: Install modules and build
        run: |
          export CC=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
          export CXX=`pwd`/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++
          echo $CXX
          yarn install && yarn build:duckdb && yarn build:addon
      - run: |
          zip -j build-arm64.zip build/Release
      - uses: actions/upload-artifact@v2
        with:
          name: node-duckdb-arm64
          path: |
            node-duckdb-arm64.zip
